#!/bin/bash

scriptName=$(basename $0)
mainBranch="master"
toDelete=$''
branches=$(git br --merged master | sed 's/[ \*]//' | grep --invert-match $mainBranch)

printHelp() {
    echo "$scriptName - List or delete your merged git branches"
    echo ""
    echo "usage:"
    echo "$scriptName COMMAND"
    echo ""
    echo "Commands:"
    echo "h, -h, --help"
    echo "	Show this help message"
    echo "-d, --delete, delete"
    echo "	Deletes all listed branches"
}

deleteBranches() {
    git branch --delete $branches
}

printDeadBranches() {
    printf "Likely safe to remove these branches:"
    printf "$toDelete\n"
}

while test $# -gt 0; do
    case "$1" in
    h|help|-h|--help)
        printHelp
        exit 0
    ;;
    -d|--delete|delete)
        doDelete=true
        shift
    ;;
    *)
        break
    ;;
    esac
done

for b in $branches; do
    toDelete="$toDelete\n\t- $b"
done;

if [ ! -z "$toDelete" ] ; then
    if [ "$doDelete" = true ]; then
        deleteBranches
        exit 0
    fi

    printDeadBranches
fi
